name: horaz
description: "Fun Messenger App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.6
  sizer: ^2.0.15

  flutter_svg: ^2.0.10+1

  shared_preferences: ^2.2.2
  hive: ^2.2.3

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  auth_buttons: ^3.0.2
  cloud_firestore: ^4.14.0
  cloud_functions: ^4.6.10
  firebase_storage: ^11.6.0
  uuid: ^4.3.3
  google_sign_in: ^6.2.1

  logger: ^2.0.2+1
  fluttertoast: ^8.2.4
  loading_indicator: ^3.1.1
  smooth_page_indicator: ^1.1.0
  fluentui_system_icons: ^1.1.229
  swipe_to: ^1.0.6
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  encrypt: ^5.0.3
  crypto: ^3.0.3

  flutter_advanced_avatar: ^1.5.0

  image_picker: ^1.0.4
#  gallery_picker: ^0.5.1
  media_picker_widget: ^1.0.7

  camerawesome: ^2.0.1
  camera: ^0.10.5+9
  video_trimmer: ^3.0.0-LTS
  video_thumbnail: ^0.5.3

  flutter_colorpicker: ^1.0.3
  screenshot: ^2.3.0

  file_picker: ^6.1.1
  open_filex: ^4.4.0
  cached_network_image: ^3.3.1
  avatar_stack: ^1.2.0
  qr_flutter: ^4.1.0
  share_plus: ^7.2.2
  percent_indicator: ^4.2.3


  video_player: ^2.8.2
#  pod_player: ^0.2.1
  stylish_bottom_bar: ^1.0.3

  flutter_firebase_chat_core: ^1.6.7
  flutter_chat_ui: ^1.6.10

  permission_handler: ^11.3.0
  contacts_service: ^0.6.3

  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  flutter_advanced_drawer: ^1.3.5
  crop_image: ^1.0.12

  zego_uikit_signaling_plugin: ^2.7.6
  zego_uikit_prebuilt_call: ^4.6.0


  audioplayers: ^5.2.0


  firebase_messaging: ^14.7.15
  awesome_notifications: ^0.8.2
  flutter_notification_channel: ^2.0.0

dependency_overrides:
  photo_manager: ^3.0.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_displaymode: ^0.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-logo.png"

flutter_native_splash:
  image: "assets/splash-logo.png"
  color: "#ffffff"
  color_dark: "#0E0847"
  image_dark: "assets/splash-logo.png"
  android_12:
    image: "assets/splash-logo.png"
    color: "#ffffff"
    image_dark: "assets/splash-logo.png"
    color_dark: "#0E0847"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/extensions/
    - assets/ringtone/
    - assets/

  fonts:
    - family: Geometria
      fonts:
        - asset: assets/fonts/Geometria.ttf
        - asset: assets/fonts/Geometria-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geometria-Medium.ttf

